apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alfresco-applicationset
  namespace: argocd
spec:
  template:
    metadata:
      name: alfresco
    spec:
      project: default
      source:
        repoURL: https://github.com/alfresco/alfresco-helm-charts
        chart: alfresco-content-services-community
        version: 3.0.1
        helm:
          valuesFiles:
            - ../apps/alfresco/alfresco.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: alfresco
      syncPolicy: {}
